### ISSUE TITLE
partition core dumped after bump to tag 10.2

### ISSUE THREAD

**Issue by fcharras** [IntelPython/dpnp#1199]
When bumping to the new tag `10.2` I have segfaults with `dpnp.partition`:

With `dpnp == 0.10.1`:

```python
import dpnp
array = dpnp.arange(9)
dpnp.partition(array, kth=3)
## works
```

With `dpnp == 0.10.2`:

```python
import dpnp
array = dpnp.arange(9)
dpnp.partition(array, kth=3)
```
output:
```
python: /tmp/dpnp/dpnp/backend/src/dpnpc_memory_adapter.hpp:172: void DPNPC_ptr_adapter<long>::depends_on(const sycl::event &) [_DataType = long]: Assertion `allocated' failed.
Aborted (core dumped)
```

**Comment by oleksandr-pavlyk** [comment]
Removing `DPNP_DEBUG = 1` on https://github.com/soda-inria/sklearn-numba-dpex/blob/main/docker/Dockerfile#L301 would disable the asserts with 0.10.2 as well.

dpnp builds published on conda do not set this flags as well.

**Comment by fcharras** [comment]
Looking at the build scrips, `DPNP_DEBUG` seems to set compile flags, for some reason i didn't think it would. Will reach out to confirm that it works if `DPNP_DEBUG` is not set.

(I probably got this variabe from [here](https://github.com/IntelPython/dpnp/blob/master/0.build.sh) )
