### ISSUE TITLE
dpnp.count_nonzero does return scalar vs.0-shape device array

### ISSUE THREAD

**Issue by samaid** [IntelPython/dpnp#1258]
This breaks the compute-follows-data concept. All dpnp functions returning scalars must return 0-shape dpnp.ndarray insteads
```python
x = np.random.random(10)
print("x:", x.device)
acc = np.count_nonzero(x <= 1.0)
print("x:", acc.device)
```

**Comment by antonwolfy** [comment]
As it was agreed, closing the issue as not a fault.
