### ISSUE TITLE
Mathematical operations with scalar don't follow data type

### ISSUE THREAD

**Issue by npolina4** [IntelPython/dpnp#1304]
[Type Promotion Rules](https://data-apis.org/array-api/latest/API_specification/type_promotion.html). 
Mixing arrays with Python scalars:
Convert the scalar to zero-dimensional array with the same data type as that of the array used in the expression.

Example:
```python
import dpnp
(dpnp.ones((2,), dtype=dpnp.float32) + 2.0).dtype
#Current out:
dtype('float64')
#Expected out:
dtype('float32')
```

**Comment by antonwolfy** [comment]
Looks the same behavior in dpctl:
```
import numpy, dpctl, dpctl.tensor as dpt

a = dpt.asarray([-3., -2., -1.,  1.,  2.,  3.], dtype=numpy.float32)
b = 2.0
(a / b).dtype
Out: dtype('float64')
```
