### ISSUE TITLE
Statistical kernels are not supported on integrated graphics

### ISSUE THREAD

**Issue by AlexanderKalistratov** [IntelPython/dpnp#1325]
Integrated graphics doesn't support `double` data type.

`cov` supports only double input and output:
https://github.com/IntelPython/dpnp/blob/cfc9b40f97d5cbc3114171728bf96e6f59b74005/dpnp/backend/kernels/dpnp_krnl_statistics.cpp#L1380

`max`, `min`, `mean`, `median`, `var` and `std` supports only double output for integer input:
https://github.com/IntelPython/dpnp/blob/cfc9b40f97d5cbc3114171728bf96e6f59b74005/dpnp/backend/kernels/dpnp_krnl_statistics.cpp#L1400

**Comment by vlad-perevezentsev** [comment]
Most statistical functions have been updated and no longer use the kernels from `dpnp_krnl_statistics.cpp` (#1396 , #1602, #1632,  #1635)
Those functions that still use kernels from this file (like `median`) have been updated to support `float` data type to run on Iris Xe #1494.

All statistical functions run on integrated graphics without support for double precision types

Example of running test_statistics on Iris XE

```
$ pytest -v tests/test_statistics.py

============================================= 1030 passed in 19.66s ==============================================

```

@AlexanderKalistratov If you don't have any additional questions, could you please close this issue?
