### ISSUE TITLE
Performance slowdown in L2-norm dpnp implementation

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/dpnp#1347]
The[ l2-norm dpnp implementation in dpbench](https://github.com/adarshyoga/dpbench/tree/main/dpbench/benchmarks/l2_norm) shows severe performance slowdown when compared to pure numpy implementation measured on CPU. 

Sapphire Rapids:
L2 norm -0.024 secs (numpy), 261.24 secs (dpnp CPU)

TigerLake:
L2 norm - 0.016 secs (numpy), 108.09 secs (dpnp CPU)

**Comment by npolina4** [comment]
Iris Xe:
Size M: L2 norm - 2.3 secs (numpy), 0.46 secs (dpnp CPU)
