### ISSUE TITLE
dpnp.sum with axis return fp64 output for fp32 input

### ISSUE THREAD

**Issue by AlexanderKalistratov** [IntelPython/dpnp#1612]
Dpnp:
```python
import dpnp as np

a = np.ones((10, 10), dtype=np.float32, device='cpu')
b = np.sum(a, axis=1)
print(b.dtype)
```

Output:
```
float64
```

Numpy:
```python
import numpy as np

a = np.ones((10, 10), dtype=np.float32)
b = np.sum(a, axis=1)
print(b.dtype)
```

Output:
```
float32
```

**Comment by antonwolfy** [comment]
The behavior here is aligned with Python array API, which [states](https://data-apis.org/array-api/latest/API_specification/generated/array_api.sum.html) about the returned type:

> The returned array must have a data type as described by the `dtype` parameter above.

while regarding input `dtype` parameter:

> if `x` has a real-valued floating-point data type, the returned array must have the default real-valued floating-point data type.

Also the same behavior while using numpy compliant with array API:
```python
import numpy.array_api as np

a = np.ones((10, 10), dtype=np.float32)
b = np.sum(a, axis=1)

print(b.dtype)
# float64
```
