### ISSUE TITLE
import dpnp gives an error

### ISSUE THREAD

**Issue by jorge221** [IntelPython/dpnp#1698]
Hi,
When importing dpnp I get this error: ImportError: libintlc.so.5: cannot open shared object file: No such file or directory

Here is the full message.

 import dpnp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jorge/.local/lib/python3.10/site-packages/dpnp/__init__.py", line 34, in <module>
    import dpctl
  File "/home/jorge/.local/lib/python3.10/site-packages/dpctl/__init__.py", line 38, in <module>
    from ._device_selection import select_device_with_aspects
  File "/home/jorge/.local/lib/python3.10/site-packages/dpctl/_device_selection.py", line 20, in <module>
    from ._sycl_device import SyclDevice, SyclDeviceCreationError
ImportError: libintlc.so.5: cannot open shared object file: No such file or directory

**Comment by antonwolfy** [comment]
Hi @jorge221,

Thank you for submitting the issue.

Could you please describe steps how you setup the environment? And how did you install or probably upgrade dpnp?
Do you have `intel-cmplr-lib-rt` package installed? And what version if present?

**Comment by jorge221** [comment]
I install dpnp using pip install dpnp. I don't have the intel-cmplr-lib-rt packages.

**Comment by jorge221** [comment]
I tried pip install intel-cmplr-lib-rt and it tells me that is already install.

**Comment by antonwolfy** [comment]
Probably you are working from activated conda environment with install `intel-cmplr-lib-rt` package there?

What command did you use to install dpnp? The same as mentioned [here](https://pypi.org/project/dpnp/0.13.0/):
```
pip install --index-url https://pypi.anaconda.org/intel/simple dpnp
```

**Comment by jorge221** [comment]
No, the one mentioned [here](https://pypi.org/project/dpnp/)

**Comment by antonwolfy** [comment]
I've checked the instruction from above [link](https://pypi.org/project/dpnp/) and couldn't reproduce the issue.

I guess there might be something in your working environment which cause an issue.
Could you please provide the output from `pip list` and `pip inspect` command from the environment where you installed dpnp?

**Comment by jorge221** [comment]
Sure. However, pip insect out is too long. I added only the dpnp part. 

pip list

Package                      Version
---------------------------- -------------
absl-py                      2.1.0
addict                       2.4.0
aiohttp                      3.8.3
aiosignal                    1.3.1
asttokens                    2.2.1
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        22.1.0
backcall                     0.2.0
bayesian-optimization        1.4.2
blinker                      1.4
cachetools                   5.3.2
certifi                      2022.9.24
cffi                         1.15.1
charset-normalizer           2.1.1
click                        8.1.3
colorama                     0.4.6
ConfigArgParse               1.5.3
contourpy                    1.0.6
cryptography                 3.4.8
cycler                       0.11.0
dash                         2.8.1
dash-core-components         2.0.0
dash-html-components         2.0.0
dash-table                   5.0.0
dataclasses                  0.6
dbus-python                  1.2.18
debugpy                      1.6.4
decorator                    5.1.1
distro                       1.7.0
distro-info                  1.1+ubuntu0.2
docopt                       0.6.2
dpcpp-cpp-rt                 2024.0.2
dpctl                        0.15.0
dpnp                         0.13.0
entrypoints                  0.4
executing                    1.2.0
fastjsonschema               2.16.3
filelock                     3.13.1
Flask                        2.2.3
flatbuffers                  23.5.26
fonttools                    4.38.0
frozenlist                   1.3.3
fsspec                       2023.12.2
gast                         0.5.4
google-auth                  2.26.2
google-auth-oauthlib         1.2.0
google-pasta                 0.2.0
grpcio                       1.60.0
h5py                         3.10.0
httplib2                     0.20.2
huggingface-hub              0.20.3
idna                         3.4
imageio                      2.26.0
importlib-metadata           4.6.4
intel-cmplr-lib-rt           2024.0.2
intel-cmplr-lic-rt           2024.0.2
intel-opencl-rt              2024.0.2
intel-openmp                 2024.0.2
ipykernel                    6.17.1
ipython                      8.7.0
ipywidgets                   8.0.4
itsdangerous                 2.1.2
jedi                         0.18.2
jeepney                      0.7.1
Jinja2                       3.1.2
joblib                       1.2.0
jsonschema                   4.17.3
jupyter_client               7.4.8
jupyter_core                 5.1.0
jupyterlab-widgets           3.0.5
keras                        2.15.0
keyring                      23.5.0
kiwisolver                   1.4.4
launchpadlib                 1.10.16
lazr.restfulclient           0.14.4
lazr.uri                     1.0.6
libclang                     16.0.6
Markdown                     3.5.2
MarkupSafe                   2.1.2
matplotlib                   3.6.2
matplotlib-inline            0.1.6
mkl                          2024.0.0
mkl-dpcpp                    2024.0.0
ml-dtypes                    0.2.0
mnist                        0.2.2
more-itertools               8.10.0
mpmath                       1.3.0
multidict                    6.0.2
nbformat                     5.5.0
nest-asyncio                 1.5.6
networkx                     2.8.8
numpoly                      1.2.5
numpy                        1.24.1
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu12            8.9.2.26
nvidia-cufft-cu12            11.0.2.54
nvidia-curand-cu12           10.3.2.106
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu12             2.18.1
nvidia-nvjitlink-cu12        12.3.101
nvidia-nvtx-cu12             12.1.105
oauthlib                     3.2.0
onemkl-sycl-blas             2024.0.0
onemkl-sycl-datafitting      2024.0.0
onemkl-sycl-dft              2024.0.0
onemkl-sycl-lapack           2024.0.0
onemkl-sycl-rng              2024.0.0
onemkl-sycl-sparse           2024.0.0
onemkl-sycl-stats            2024.0.0
onemkl-sycl-vm               2024.0.0
open3d                       0.16.0
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.5.1
parso                        0.8.3
pexpect                      4.8.0
pickleshare                  0.7.5
Pillow                       9.3.0
pip                          24.0
pipreqs                      0.4.11
platformdirs                 2.5.4
plotly                       5.13.1
pooch                        1.7.0
probreg                      0.3.6
prompt-toolkit               3.0.33
protobuf                     4.23.4
psutil                       5.9.4
ptyprocess                   0.7.0
pure-eval                    0.2.2
pyacvd                       0.2.9
pyaml                        21.10.1
pyasn1                       0.5.1
pyasn1-modules               0.3.0
pybaselines                  1.0.0
pybind11                     2.10.1
pycparser                    2.21
Pygments                     2.13.0
PyGObject                    3.42.1
PyJWT                        2.3.0
pymeshfix                    0.16.2
pyparsing                    2.4.7
pyquaternion                 0.9.9
pyrsistent                   0.19.3
python-apt                   2.4.0+ubuntu2
python-dateutil              2.8.2
pytz                         2022.6
pyvista                      0.38.4
PyYAML                       5.4.1
pyzmq                        24.0.1
regex                        2023.12.25
requests                     2.28.1
requests-oauthlib            1.3.1
rsa                          4.9
ruamel.yaml                  0.17.21
ruamel.yaml.clib             0.2.7
sacremoses                   0.1.1
safetensors                  0.4.1
scikit-learn                 1.2.0
scipy                        1.9.3
scooby                       0.7.1
SecretStorage                3.3.1
sentencepiece                0.1.99
setuptools                   59.6.0
six                          1.16.0
soundfile                    0.11.0
ssh-import-id                5.11
stack-data                   0.6.2
sympy                        1.12
systemd-python               234
tbb                          2021.11.0
tenacity                     8.2.2
tensorboard                  2.15.1
tensorboard-data-server      0.7.2
tensorflow                   2.15.0.post1
tensorflow-cpu               2.15.0.post1
tensorflow-estimator         2.15.0
tensorflow-io-gcs-filesystem 0.35.0
termcolor                    2.4.0
tetgen                       0.6.2
threadpoolctl                3.1.0
tokenizers                   0.15.0
torch                        2.1.2
torchaudio                   2.1.2
torchvision                  0.16.2
tornado                      6.2
tqdm                         4.64.1
traitlets                    5.6.0
transformers                 4.37.0
transforms3d                 0.4.1
triton                       2.1.0
typing_extensions            4.9.0
ubuntu-advantage-tools       8001
unattended-upgrades          0.1
urllib3                      1.26.13
vtk                          9.2.6
wadllib                      1.3.6
wcwidth                      0.2.5
Werkzeug                     2.2.3
wfdb                         4.1.0
wheel                        0.37.1
widgetsnbextension           4.0.5
wrapt                        1.14.1
wslink                       1.9.1
yarg                         0.1.9
yarl                         1.8.1
zipp                         1.0.0

pip inspect

{
      "metadata": {
        "metadata_version": "2.1",
        "name": "dpnp",
        "version": "0.13.0",
        "platform": [
          "Linux",
          "Windows"
        ],
        "summary": "Data Parallel Extension for NumPy",
        "description_content_type": "text/markdown",
        "keywords": [
          "sycl",
          "numpy",
          "python3",
          "intel",
          "mkl",
          "oneapi",
          "gpu",
          "dpcpp"
        ],
        "home_page": "https://github.com/IntelPython/dpnp",
        "author": "Intel Corporation",
        "license": "Apache 2.0",
        "classifier": [
          "Development Status :: 4 - Beta",
          "Intended Audience :: Science/Research",
          "Intended Audience :: Developers",
          "License :: OSI Approved :: Apache Software License",
          "Programming Language :: C++",
          "Programming Language :: Cython",
          "Programming Language :: Python",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3.8",
          "Programming Language :: Python :: 3.9",
          "Programming Language :: Python :: 3.10",
          "Programming Language :: Python :: 3.11",
          "Programming Language :: Python :: Implementation :: CPython",
          "Topic :: Software Development",
          "Topic :: Scientific/Engineering",
          "Operating System :: Microsoft :: Windows",
          "Operating System :: POSIX",
          "Operating System :: Unix"
        ],
        "requires_dist": [
          "dpctl",
          "dpcpp-cpp-rt",
          "mkl-dpcpp",
          "numpy"
        ],
        "description": "[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)\n[![Imports: isort](https://img.shields.io/badge/%20imports-isort-%231674b1?style=flat&labelColor=ef8336)](https://pycqa.github.io/isort/)\n[![Pre-commit](https://github.com/IntelPython/dpnp/actions/workflows/pre-commit.yml/badge.svg?branch=master&event=push)](https://github.com/IntelPython/dpnp/actions/workflows/pre-commit.yml)\n[![Conda package](https://github.com/IntelPython/dpnp/actions/workflows/conda-package.yml/badge.svg?branch=master&event=push)](https://github.com/IntelPython/dpnp/actions/workflows/conda-package.yml)\n[![Coverage Status](https://coveralls.io/repos/github/IntelPython/dpnp/badge.svg?branch=master)](https://coveralls.io/github/IntelPython/dpnp?branch=master)\n[![Build Sphinx](https://github.com/IntelPython/dpnp/workflows/Build%20Sphinx/badge.svg)](https://intelpython.github.io/dpnp)\n\n# DPNP - Data Parallel Extension for NumPy*\n[API coverage summary](https://intelpython.github.io/dpnp/reference/comparison.html#summary)\n\n[Full documentation](https://intelpython.github.io/dpnp/)\n\n[DPNP C++ backend documentation](https://intelpython.github.io/dpnp/backend_doc/)\n\n## Build from source:\nEnsure you have the following prerequisite packages installed:\n\n- `cython`\n- `cmake >=3.21`\n- `dpcpp_linux-64` or `dpcpp_win-64` (depending on your OS)\n- `dpctl`\n- `mkl-devel-dpcpp`\n- `onedpl-devel`\n- `ninja`\n- `numpy >=1.19,<1.25a0`\n- `python`\n- `scikit-build`\n- `setuptools`\n- `sysroot_linux-64 >=2.28` (only on Linux OS)\n- `tbb-devel`\n\nAfter these steps, `dpnp` can be built in debug mode as follows:\n\n```bash\ngit clone https://github.com/IntelPython/dpnp\ncd dpnp\npython scripts/build_locally.py\n```\n\n## Install Wheel Package via pip\nInstall DPNP\n```cmd\npython -m pip install --index-url https://pypi.anaconda.org/intel/simple dpnp\n```\n\nSet path to Performance Libraries in case of using venv or system Python:\n```cmd\nexport LD_LIBRARY_PATH=<path_to_your_env>/lib\n```\n\nIt is also required to set following environment variables:\n```cmd\nexport OCL_ICD_FILENAMES_RESET=1\nexport OCL_ICD_FILENAMES=libintelocl.so\n```\n\n## Run test\n```bash\npytest\n# or\npytest tests/test_matmul.py -s -v\n# or\npython -m unittest tests/test_mixins.py\n```\n\n## Run numpy external test\n```bash\n. ./0.env.sh\npython -m tests.third_party.numpy_ext\n# or\npython -m tests.third_party.numpy_ext core/tests/test_umath.py\n# or\npython -m tests.third_party.numpy_ext core/tests/test_umath.py::TestHypot::test_simple\n```\n\n### Building documentation:\n```bash\nPrerequisites:\n$ conda install sphinx sphinx_rtd_theme\nBuilding:\n1. Install dpnp into your python environment\n2. $ cd doc && make html\n3. The documentation will be in doc/_build/html\n```\n\n## Packaging:\n```bash\n. ./0.env.sh\nconda-build conda-recipe/\n```\n\n## Run benchmark:\n```bash\ncd benchmarks/\n\nasv run --python=python --bench <filename without .py>\n# example:\nasv run --python=python --bench bench_elementwise\n\n# or\n\nasv run --python=python --bench <class>.<bench>\n# example:\nasv run --python=python --bench Elementwise.time_square\n\n# add --quick option to run every case once but looks like first execution has additional overheads and takes a lot of time (need to be investigated)\n```\n\n\n## Tests matrix:\n| # |Name                                |OS   |distributive|interpreter|python used from|SYCL queue manager|build commands set                                                                                                                              |forced environment                                                                                                       |\n|---|------------------------------------|-----|------------|-----------|:--------------:|:----------------:|------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|\n|1  |Ubuntu 20.04 Python37               |Linux|Ubuntu 20.04|Python 3.7 |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace pytest                                 |cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis                                                 |\n|2  |Ubuntu 20.04 Python38               |Linux|Ubuntu 20.04|Python 3.8 |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace pytest                                 |cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis                                                 |\n|3  |Ubuntu 20.04 Python39               |Linux|Ubuntu 20.04|Python 3.9 |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace pytest                                 |cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis                                                 |\n|4  |Ubuntu 20.04 External Tests Python37|Linux|Ubuntu 20.04|Python 3.7 |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace python -m tests_external.numpy.runtests|cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis                                                 |\n|5  |Ubuntu 20.04 External Tests Python38|Linux|Ubuntu 20.04|Python 3.8 |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace python -m tests_external.numpy.runtests|cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis                                                 |\n|6  |Ubuntu 20.04 External Tests Python39|Linux|Ubuntu 20.04|Python 3.9 |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace python -m tests_external.numpy.runtests|cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis                                                 |\n|7  |Code style                          |Linux|Ubuntu 20.04|Python 3.8 |  IntelOneAPI   |      local       |python ./setup.py style                                                                                                                         |cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis, conda-verify, pycodestyle, autopep8, black     |\n|8  |Valgrind                            |Linux|Ubuntu 20.04|           |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace                                        |cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis                                                 |\n|9  |Code coverage                       |Linux|Ubuntu 20.04|Python 3.8 |  IntelOneAPI   |      local       |export DPNP_DEBUG=1 python setup.py clean python setup.py build_clib python setup.py build_ext --inplace                                        |cmake-3.19.2, valgrind, pytest-valgrind, conda-build, pytest, hypothesis, conda-verify, pycodestyle, autopep8, pytest-cov|\n"
      },
      "metadata_location": "/home/jorge/.local/lib/python3.10/site-packages/dpnp-0.13.0.dist-info",
      "installer": "pip",
      "requested": true
    }

**Comment by antonwolfy** [comment]
@jorge221, thank you for the provided info!

Could you please make sure the environment variable `LD_LIBRARY_PATH` is set properly, as mentioned [here](https://pypi.org/project/dpnp/):
```
export LD_LIBRARY_PATH=<path_to_your_env>/lib
```
Could you please check that you have the files:
```
$LD_LIBRARY_PATH/libintlc.so
$LD_LIBRARY_PATH/libintlc.so.5
```

I've got the same import error when `LD_LIBRARY_PATH` is not set. And the issue was gone, one I set it to `<path_to_your_env>/lib`:
```
$ ls -la $LD_LIBRARY_PATH/libintlc.so
-rwxr-xr-x 1 xantvol xantvol 21 Feb  9 18:46 /home/xantvol/tmp/pip/.venv/lib/libintlc.so
$ ls -la $LD_LIBRARY_PATH/libintlc.so.5
-rwxr-xr-x 1 xantvol xantvol 408152 Feb  9 18:46 /home/xantvol/tmp/pip/.venv/lib/libintlc.so.5
```
where I have packages in the environment:
```
$ pip list
Package                 Version
----------------------- ---------
dpcpp-cpp-rt            2024.0.2
dpctl                   0.15.0
dpnp                    0.13.0
intel-cmplr-lib-rt      2024.0.2
intel-cmplr-lic-rt      2024.0.2
intel-opencl-rt         2024.0.2
intel-openmp            2024.0.2
mkl                     2024.0.0
mkl-dpcpp               2024.0.0
numpy                   1.26.4
onemkl-sycl-blas        2024.0.0
onemkl-sycl-datafitting 2024.0.0
onemkl-sycl-dft         2024.0.0
onemkl-sycl-lapack      2024.0.0
onemkl-sycl-rng         2024.0.0
onemkl-sycl-sparse      2024.0.0
onemkl-sycl-stats       2024.0.0
onemkl-sycl-vm          2024.0.0
pip                     24.0
setuptools              58.1.0
tbb                     2021.11.0
```

**Comment by antonwolfy** [comment]
@jorge221, please let me know if you manage to resolve the issue or if any additional help is needed.

**Comment by antonwolfy** [comment]
@jorge221, please let me know if the issue is still visible and I'll reopen the case.
