### ISSUE TITLE
ModuleNotFoundError: No module named 'dpnp.dpnp_algo.dpnp_algo'

### ISSUE THREAD

**Issue by purohitank** [IntelPython/dpnp#1731]
Hello,

I installed the dpnp package on Windows 11 via WSL.

I have made the following linkings 

export LD_LIBRARY_PATH=<path_to_your_env>/lib
$LD_LIBRARY_PATH/libintlc.so
$LD_LIBRARY_PATH/libintlc.so.5

But still am getting this error

from dpnp.dpnp_algo.dpnp_algo import *
ModuleNotFoundError: No module named 'dpnp.dpnp_algo.dpnp_algo'

Thank you in advance for your help

**Comment by purohitank** [comment]
Here is pip list

Package                 Version
----------------------- ---------
dpcpp-cpp-rt            2024.0.0
dpctl                   0.15.0
dpnp                    0.13.0
intel-cmplr-lib-rt      2024.0.0
intel-cmplr-lic-rt      2024.0.0
intel-opencl-rt         2024.0.0
intel-openmp            2024.0.0
mkl                     2024.0.0
mkl-dpcpp               2024.0.0
mkl-fft                 1.3.8
mkl-random              1.2.4
mkl-service             2.4.0
mkl-umath               0.1.1
numpy                   1.24.4
onemkl-sycl-blas        2024.0.0
onemkl-sycl-datafitting 2024.0.0
onemkl-sycl-dft         2024.0.0
onemkl-sycl-lapack      2024.0.0
onemkl-sycl-rng         2024.0.0
onemkl-sycl-sparse      2024.0.0
onemkl-sycl-stats       2024.0.0
onemkl-sycl-vm          2024.0.0
pip                     23.3.1
setuptools              68.2.2
six                     1.16.0
tbb                     2021.11.0
tbb4py                  2021.11.0
wheel                   0.41.2

**Comment by antonwolfy** [comment]
@purohitank , thank you reporting the issue.

I guess the problem might appear if your current directory is a folder with DPNP repository.

Like if I cloned DPNP repo to `~/code/dpnp` and I'm trying to import from it I'll get the same error:
```bash
~/code/dpnp$ python -c "import dpnp"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xantvol/code/dpnp/dpnp/__init__.py", line 55, in <module>
    from dpnp.dpnp_iface import *
  File "/home/xantvol/code/dpnp/dpnp/dpnp_iface.py", line 49, in <module>
    from dpnp.dpnp_algo import *
  File "/home/xantvol/code/dpnp/dpnp/dpnp_algo/__init__.py", line 27, in <module>
    from dpnp.dpnp_algo.dpnp_algo import *
ModuleNotFoundError: No module named 'dpnp.dpnp_algo.dpnp_algo'
```
But if I change it to let say to `~/code/`, then the issue is gone:
```bash
~/code$ python -c "import dpnp"
~/code$
```
Please let me know if it helps.

**Comment by purohitank** [comment]
Hi Anton,

Thank you for your feedback.

That was indeed the problem. Not using the repo directory solved the issue for me.
