### ISSUE TITLE
numpy.digitize

### ISSUE THREAD

**Issue by cfkstat** [IntelPython/dpnp#1829]
When can numpy.digitize be implemented with a parallel version?

**Comment by vlad-perevezentsev** [comment]
Hi @cfkstat,

Thank you for your request regarding the parallel implementation of `dpnp.digitize()`.
This function has been implemented in #1847. These changes will be available in the upcoming dpnp 0.15.0 release.

If you have any additional questions, feel free to ask.

**Comment by vlad-perevezentsev** [comment]
@cfkstat If you don't have any additional questions about this function, could you please close this issue?
