### ISSUE TITLE
Reflect required numpy version in Pypi json

### ISSUE THREAD

**Issue by icfaust** [IntelPython/dpnp#1942]
While the listed numpy version is available here: https://github.com/IntelPython/dpnp and here: https://pypi.org/project/dpnp/, when installed it is up to the user to check this when installing from pip.  Please adapt the published json here: https://pypi.org/pypi/dpnp/json the "required_dist" should be ```["dpctl","dpcpp-cpp-rt","mkl-dpcpp","numpy<1.25a0,>=1.19"]``` instead of ```["dpctl","dpcpp-cpp-rt","mkl-dpcpp","numpy"]``` . This will make this requirement enforced on dpnp installation from pip.

**Comment by icfaust** [comment]
@antonwolfy Any news on this? It seems that the pypi information for the release a couple days ago is the same.

**Comment by antonwolfy** [comment]
@icfaust , it was intentional, because dpnp from `0.16.0` release can work now with any numpy version, including `numpy>2.0`.

**Comment by icfaust** [comment]
@antonwolfy then the documentation on pypi is wrong for build from source

**Comment by antonwolfy** [comment]
@icfaust, i see, thank you for noticing that!
