### ISSUE TITLE
dpnp.dparray changes to enable zero-copy interoperability with other Python SYCL extensions

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpnp#217]
The `dpnp.dparray` implementation needs changes to support bi-directional zero-copy data exchange with other SYCL-based Python extensions, such as `numba-dppy`, `daal4py`, `torch_ipex`.

1. Implement the [``__sycl_usm_array_interface__``](https://github.com/IntelPython/dpctl/wiki/Zero-copy-data-exchange-using-SYCL-USM) property inside `dparray`.
2. Allow Python objects `__sycl_usm_array_interface__` to be given as arguments to `dparray` constructor to allow `dparray` to assume ownership of their USM memory. Note: An implementation of the `__sycl_usm_array_interface__` can be found in [`dpctl.memory._memory`](https://github.com/IntelPython/dpctl/blob/master/dpctl/memory/_memory.pyx).
3. `dpnp.dparray` should implement a method to retrieve the SYCL object (`queue` or `context`) using which the USM memory was allocated.

**Comment by shssf** [comment]
I looks like it will not be implemented in DPNP.
