### ISSUE TITLE
dpnp_utils.copy_values_to_dparray: add suppurt of 0-d arrays

### ISSUE THREAD

**Issue by Alexander-Makaryev** [IntelPython/dpnp#253]
Test case for example:
`tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_array_from_numpy_scalar`
Error occurs when 0-dimensional array (scalar) is provided (at the same time all other checks in function are passed):
```
E     File "dpnp/backend.pyx", line 95, in dpnp.backend.dpnp_array
E       cpdef dparray dpnp_array(obj, dtype=None):
E     File "dpnp/backend.pyx", line 114, in dpnp.backend.dpnp_array
E       copy_values_to_dparray(result, obj)
E     File "dpnp/dpnp_utils.pyx", line 128, in dpnp.dpnp_utils.copy_values_to_dparray
E       for elem_value in input_obj:
E   iteration over a 0-d array
```

**Comment by vtavana** [comment]
With dpnp 0.16.0

tests/third_party/cupy/creation_tests/test_from_data.py::TestFromData::test_array_from_numpy_scalar PASSED
