### ISSUE TITLE
dpctl library name update - libDPPLSyclInterface.so --> libDPCTLSyclInterface.so 

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/dpnp#374]
The dpctl library names need to be updated (https://github.com/IntelPython/dpnp/blob/master/setup.py#L156) from `libDPPLSyclInterface.so` -> `libDPCTLSyclInterface.so`.

@shssf @Alexander-Makaryev

**Comment by samir-nasibli** [comment]
@reazulhoque Thank you for the report! 
@shssf fix on #376. Please, take a look.
