### ISSUE TITLE
Check dpCtl >=0.5.0 to cope with new library name

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpnp#379]
Please, insert check before this line:
https://github.com/IntelPython/dpnp/blob/e8aafe3b2996a4a766289523b0cbaf7e7805a9c3/setup.py#L156

Change version dpctl >= 0.5.0 (rc should be included):
https://github.com/IntelPython/dpnp/blob/e8aafe3b2996a4a766289523b0cbaf7e7805a9c3/conda-recipe/meta.yaml#L13
https://github.com/IntelPython/dpnp/blob/e8aafe3b2996a4a766289523b0cbaf7e7805a9c3/conda-recipe/meta.yaml#L17

@Vyacheslav-Smirnov Do you know how to point to versions including 0.5.0rc1, 0.5.0, but not 0.4.0? How to make it without using `rc` suffix version name? Maybe >=0.5 ?

**Comment by Alexander-Makaryev** [comment]
PR https://github.com/IntelPython/dpnp/pull/380

**Comment by Vyacheslav-Smirnov** [comment]
>> "Do you know how to point to versions including 0.5.0rc1, 0.5.0, but not 0.4.0? How to make it without using rc suffix version name? Maybe >=0.5 ?"
I think this should be correct

**Comment by shssf** [comment]
Fixed
