### ISSUE TITLE
dpnp4.0 dpnp.linalg.det does not compute anything for ndim == 2

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/dpnp#494]
[Please look here](https://github.com/IntelPython/dpnp/blob/0.4.0/dpnp/backend/custom_kernels_linalg.cpp#L92). I read it as if number of dimension is 2 we simply do nothing. Does this look correct?

**Comment by Alexander-Makaryev** [comment]
@reazulhoque
This behavior is already fixed in master branch
https://github.com/IntelPython/dpnp/blob/master/dpnp/backend/kernels/dpnp_krnl_linalg.cpp#L84
Covered by tests
https://github.com/IntelPython/dpnp/blob/master/tests/test_linalg.py#L58
Fix will be available in next release.

**Comment by Rubtsowa** [comment]
In master this fixed. If you clone master and build dpnp, you can check this in python, for example:
>>> import dpnp
Running on: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
queue initialization time: 0.140196 (sec.)
SYCL kernels link time: 0.0338662 (sec.)

>>> a=dpnp.array([[1, 2], [3, 4]])
>>> dpnp.linalg.det(a)
-2
