### ISSUE TITLE
dependency for install

### ISSUE THREAD

**Issue by zjin-lcf** [IntelPython/dpnp#51]
Can you please update the README for installation using, for example, beta08 ?

dpnp/backend/custom_kernels_statistics.cpp:34:22: error: no member named 'mkl'                                                      in namespace 'oneapi'; did you mean simply 'mkl'?
namespace mkl_blas = oneapi::mkl::blas::row_major;
                     ^~~~~~~~~~~
                     mkl
/opt/intel/oneapi/mkl/2021.1-beta08/include/mkl_blas_sycl_usm.hpp:26:11: note:                                                      'mkl' declared here
namespace mkl {
          ^
dpnp/backend/custom_kernels_statistics.cpp:97:33: error: no member named 'mkl'                                                      in namespace 'oneapi'; did you mean simply 'mkl'?
                                oneapi::mkl::uplo::upper,         // uplo upper                                                     _lower,
                                ^~~~~~~~~~~
                                mkl
/opt/intel/oneapi/mkl/2021.1-beta08/include/mkl_blas_sycl_usm.hpp:26:11: note:                                                      'mkl' declared here
namespace mkl {
          ^
dpnp/backend/custom_kernels_statistics.cpp:98:33: error: no member named 'mkl'                                                      in namespace 'oneapi'; did you mean simply 'mkl'?
                                oneapi::mkl::transpose::nontrans, // transpose                                                      trans,
                                ^~~~~~~~~~~
                                mkl
/opt/intel/oneapi/mkl/2021.1-beta08/include/mkl_blas_sycl_usm.hpp:26:11: note:                                                      'mkl' declared here
namespace mkl {

**Comment by Alexander-Makaryev** [comment]
@zjin-lcf 
It is best to update oneAPI installation to beta09.
But if you want to continue using beta08 then replace `oneapi::mkl` with `mkl` in sources.
We are not planning to support old beta-versions of oneAPI.

**Comment by zjin-lcf** [comment]
Thanks.
