### ISSUE TITLE
call_origin means such function can't executed in GPU?

### ISSUE THREAD

**Issue by wdkwyf** [IntelPython/dpnp#834]
Hi, I want to use dpnp.convolve, but the source code:
`    return call_origin(numpy.convolve, a=a, v=v, mode=mode)
`
So, I wonder whether this function can be execued in GPU or not? Thank you for your patience.

**Comment by samir-nasibli** [comment]
Hi @wdkwyf!
Your guesses are correct. Currently this function is only supported at the API level, the call makes a fallback on `numpy`, which executes only on CPU.
Thank you!
